### ISSUE TITLE
Aria2 在下载过程中对容器使用 stop / kill 关闭无效

### ISSUE THREAD

**Issue by LamGC** [P3TERX/Docker-Aria2-Pro#14]
使用 Docker 重启 Aria2-pro 容器时发生卡死，关闭前 Aria2 正在进行下载，日志显示进程管理似乎已经执行了 finish 脚本，但查看 Portainer 的容器进程列表中 `aria2c` 进程依然在运行中：
![QQ截图20200815143020](https://user-images.githubusercontent.com/16975255/90306881-e3ebd180-df03-11ea-8d44-fb2f76eb14d7.png)

已尝试使用 `docker stop` 和 `docker kill` 关闭容器但失败（命令执行会卡住，然后返回，`docker ps` 显示容器依然正在运行），重启服务器后 Docker 显示容器状态为 `DEAD`，可以删除容器。

网上查找资料说是由于容器进程处于`D状态`（不是很懂），只能重启（[链接](https://www.jianshu.com/p/813d8362d497)）。

关闭日志内容：
```
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] kill-aria2c: executing... ,
[cont-finish.d] kill-aria2c: exited 0.,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
s6-svwait: fatal: timed out,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by LamGC** [comment]
使用镜像版本：p3terx/aria2-pro:latest  ->  a5fa3522c2d3

**Comment by P3TERX** [comment]
你这个情况我没办法复现。根据你提供的 D状态 那个资料分析，可能是因为下载时有大量数据写入，占用了大量的IO资源，然后突然关闭导致系统反应不过来。因为前面的指令还在等待，所以后续持续发送关闭操作指令也没办法接收。其实这个情况只能等，操作太多只能添乱。

建议不要在有下载任务的时候重启，重启要先暂停任务。

**Comment by LamGC** [comment]
了解了，感谢解答。:D
