### ISSUE TITLE
docker通过portainer配置后怎么限制日志文件大小呢

### ISSUE THREAD

**Issue by q350348361** [P3TERX/Docker-Aria2-Pro#16]
我不是很懂docker，只是很基础的使用还可以，用portainer添加aria2后发现'--log-opt max-size=1m'这个配置没有对应的位置添加，不知道怎么操作

**Comment by q350348361** [comment]
> 我不是很懂docker，只是很基础的使用还可以，用portainer添加aria2后发现'--log-opt max-size=1m'这个配置没有对应的位置添加，不知道怎么操作

是通过Logging—add logging driver option添加个max-size=1M吗？

**Comment by P3TERX** [comment]
没用过 portainer ，这个帮不了你。
直接 CLI 粘贴一把梭多方便
