### ISSUE TITLE
内存占用大

### ISSUE THREAD

**Issue by Hkiller** [P3TERX/docker-aria2-pro#2]
docker开启后，开始下载任务，内存占用直线上升，会一直升到我设置的内存限制上限，而且在下载完成后仍然保持很大的内存占用。这是正常的情况么？
![微信截图_20200310103625](https://user-images.githubusercontent.com/20572390/76274430-a8e1d400-62bb-11ea-8ca0-2a4fcac049e9.png)

**Comment by P3TERX** [comment]
内存占用跟你设置的缓存大小和正在下载的任务数有关
