### ISSUE TITLE
未知原因丢失了20多个任务

### ISSUE THREAD

**Issue by Masterbaiter** [P3TERX/Docker-Aria2-Pro#20]
今天更新了一下debian系统（不知道与更新是否有关系），发现丢失了20多个下载任务。

我用的是ariang图形界面，同时下载任务比较多有200多个，突然发现莫名其妙的少了20多个（看不出有什么规律，似乎是随机丢失了）。去下载目录看这些未完成的文件都还在，xxx.aria2的文件也都在，但却不再下载了。不知道这是不是BUG
  
然后下面是导出LOG返回的不知道是否有关的信息：
出现了一些
curl: (7) Failed to connect to localhost port 6800: Connection refused
以及所有下载任务都返回
ls: /downloads/LAND_AND_FREEDOM.aria2__temp: No such file or directory
不知道为什么会寻找.aria2_temp的后缀名，我看下载目录只有.aria2的后缀名。
  
总之现在的问题就是莫名其妙的丢失了20多个任务，其他的都继续正常下载，有没有什么思路可以troubleshoot呢？

**Comment by P3TERX** [comment]
https://p3terx.com/archives/docker-aria2-pro.html/comment-page-1#comment-1102
![image](https://user-images.githubusercontent.com/25927179/102689647-b5c42880-423a-11eb-9d6b-1b00625d89a5.png)

博客中的应该也是你的留言吧，已经回复了。

然后补充一点，如果要同时下载非常多的任务，建议对线程数进行合理的限制。

https://github.com/P3TERX/aria2.conf/blob/9a20d2e75450469ddc2f51e5a249189b16b2e1a0/aria2.conf#L183
