### ISSUE TITLE
指定bt端口，请求tracker时仍然使用的是6888

### ISSUE THREAD

**Issue by latel** [P3TERX/docker-aria2-pro#3]
![image](https://user-images.githubusercontent.com/5621862/77111939-21d2ef80-6a63-11ea-9fe6-b23c31f2f084.png)

![image](https://user-images.githubusercontent.com/5621862/77112151-7a09f180-6a63-11ea-8034-317ca4b56538.png)

**Comment by latel** [comment]
看了官方文档，说是配置文件里的端口是无效的，实际的端口是命令行通过port map指定的，可是我用的是docker-compose啊，因为我实际上是部署在反向代理后面，所以使用的是expose而不是port， 并且我尝试使用map也是没用的。

![image](https://user-images.githubusercontent.com/5621862/77141295-553f6980-6ab7-11ea-86e7-dba205006231.png)

**Comment by P3TERX** [comment]
显示的端口是容器内的固定的，实际端口是你映射的。

**Comment by xclidongbo** [comment]
实际，bt下载一点速度都没有。
