### ISSUE TITLE
完成任务后自动移动到指定文件夹？

### ISSUE THREAD

**Issue by wmjlxl** [P3TERX/docker-aria2-pro#4]
大佬，

请问 完成任务后可否用脚本实现 自动移动 文件&文件夹 到指定文件夹？

例如我的下载目录为 /download, 下载好的 文件 a.txt 或是 A 文件夹，想用脚本自动实现 把 a.txt & A 自动移动到 /download/done 下？

谢谢大神。

**Comment by wmjlxl** [comment]
我搜索然后按照网上的弄了个 arai2-done.sh 内容如下：
#!/bin/bash
mv $3 /downloads/done

然后在 airai2.conf 里设置:
on-download-complete=/config/aria2-done.sh

然而并没有实现。。。

**Comment by P3TERX** [comment]
这个需求似乎很多人有，我个人也觉得不错，所以 [P3TERX/aria2.conf](https://github.com/P3TERX/aria2.conf) 项目已经添加相关脚本。

目前需要手动进行配置，等有空了整合到 Aria2 Pro 中，做成一键配置。

使用方式是先按照说明文档先解除固定配置，然后下载脚本并修改相关配置项：`on-download-complete=move.sh`，最后重启。

**Comment by wmjlxl** [comment]
> 这个需求似乎很多人有，我个人也觉得不错，所以 [P3TERX/aria2.conf](https://github.com/P3TERX/aria2.conf) 项目已经添加相关脚本。
> 
> 目前需要手动进行配置，等有空了整合到 Aria2 Pro 中，做成一键配置。
> 
> 使用方式是先按照说明文档先解除固定配置，然后下载脚本并修改相关配置项：`on-download-complete=move.sh`，最后重启。

给力。但是有个问题。
就是我在群晖stop 了 Aria2-Pro docker, 然后修改 aria2.conf 里的 
on-download-complete=/config/**delete.aria2.sh**
->
on-download-complete=/config/**move.sh**

发现开启 docker  后，自动变回原来的 delete.aria2.sh

请问这个怎么解决呢？

**Comment by P3TERX** [comment]
为了保护配置不被改乱，做的修复措施。在配置目录下新建一个名为 `helloworld` 的文件，解锁限制，然后再改配置文件，这个教程中有说明。

**Comment by wmjlxl** [comment]
> 为了保护配置不被改乱，做的修复措施。在配置目录下新建一个名为 `helloworld` 的文件，解锁限制，然后再改配置文件，这个教程中有说明。

谢谢，但是我在你网站找来相关 aria2 文章，并没有 helloworld 的出现。

刚试了一下， /config 下 加了个 helloworld 空白文件，然而docker 重启后 aira2.conf 还是被重置了。。。

**Comment by P3TERX** [comment]
更新版本，你可能还在旧版本

**Comment by wmjlxl** [comment]
![Screen Shot 2020-04-16 at 11 01 01 PM](https://user-images.githubusercontent.com/22372603/79472224-2674ce80-8036-11ea-93fd-eb1d16b372c5.png)

明白了，我尝试，停止 docker，删除 aria2 docker 和 镜像，然后 把 docker app stop 掉，重新开启。 docker 里搜索  p3terx-aria2-pro, 重新下载 镜像。

还是一样的情况。我明天再试一试把。

再次感谢你的回复。

**Comment by wmjlxl** [comment]
今天有时间重新 群晖 docker 安装了，再次测试失败。

看来是群晖 docker 问题了？
