### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by JLover0712** [P3TERX/docker-aria2-pro#7]
用OMV运行docker的时候提示出现
Could not execute user command: /config/move.sh: Permission denied
在机器上、容器里都给move.sh加了可执行的权限，结果运行的时候权限又会自动改回来，并且还是不能运行，请问有解决的方法嘛

**Comment by P3TERX** [comment]
![image](https://user-images.githubusercontent.com/25927179/84875136-23d73980-b0b8-11ea-95ed-ecb3e3c02253.png)

https://p3terx.com/archives/problems-and-solutions-encountered-in-using-openmediavault-1.html
