### ISSUE TITLE
自定义下载目录下的问题

### ISSUE THREAD

**Issue by Genion** [P3TERX/docker-aria2-pro#9]
使用/downloads/电影/xxx  自定义下载目录时，在配置好自动上传后，

出现的问题
1.部分媒体文件丢失（已经下载完毕）
2.部分带有.aria2和媒体文件一起上传，导致无法播放
3.http下载.torrent 会先上传并创建目录 /电影/xxx ，然后电影下完后又重复创建目录 /电影/xxx

**Comment by P3TERX** [comment]
之前脚本不支持前端自定义下载目录，现在新版已经支持。更新即可
